import type { InquiryStatus } from "./admin-api";

export type AdminLocale = "de" | "en";

export const adminLocales: AdminLocale[] = ["de", "en"];

export const adminCopy = {
  de: {
    language: "Sprache",
    administration: "Administration",
    loading: "Administration wird geladen...",
    logout: "Abmelden",
    loggingOut: "Abmeldung...",
    logoutError: "Die Abmeldung konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.",
    login: {
      title: "Anmelden",
      intro: "Melden Sie sich mit Ihrem autorisierten SB Power Konto an.",
      email: "E-Mail",
      password: "Passwort",
      showPassword: "Passwort anzeigen",
      hidePassword: "Passwort verbergen",
      submit: "Anmelden",
      submitting: "Anmeldung...",
      checking: "Sitzung wird geprüft...",
      error: "E-Mail oder Passwort ist nicht korrekt.",
    },
    list: {
      kicker: "Kundenservice",
      title: "Kontaktanfragen",
      intro: "Neue Kundenanfragen prüfen und den Bearbeitungsstatus verwalten.",
      summary: "Zusammenfassung",
      newRequests: "Neue Anfragen",
      contacted: "Kontaktiert",
      closed: "Abgeschlossen",
      searchLabel: "Nach Kunde suchen",
      searchPlaceholder: "Nach Kunde suchen...",
      filterLabel: "Status filtern",
      allStatuses: "Alle Status",
      loading: "Anfragen werden geladen...",
      loadError: "Die Kontaktanfragen konnten nicht geladen werden.",
      emptyTitle: "Keine Kontaktanfragen vorhanden.",
      emptyText: "Neue Anfragen erscheinen hier, sobald Kunden das Formular senden.",
      noResultsTitle: "Keine passenden Anfragen gefunden.",
      noResultsText: "Passen Sie die Suche oder den Statusfilter an.",
      previousPage: "Zurück",
      nextPage: "Weiter",
      pageInfo: (page: number, totalPages: number) => `Seite ${page} von ${totalPages}`,
      columns: { status: "Status", name: "Name", service: "Leistung", phone: "Telefon", email: "E-Mail", date: "Datum", action: "Aktion" },
      open: "Anfrage öffnen",
      openFor: (name: string) => `Anfrage von ${name} öffnen`,
    },
    detail: {
      back: "Zurück zu den Anfragen",
      request: "Kontaktanfrage",
      received: "Eingegangen am",
      customer: "Kunde",
      name: "Name",
      phone: "Telefon",
      email: "E-Mail",
      service: "Leistung",
      message: "Nachricht",
      notProvided: "Nicht angegeben",
      noMessage: "Keine Nachricht angegeben.",
      contactCustomer: "Kunden kontaktieren",
      call: "Anrufen",
      writeEmail: "E-Mail schreiben",
      status: "Status",
      saved: "Status gespeichert",
      loadError: "Diese Kontaktanfrage konnte nicht geladen werden.",
      saveError: "Der Status konnte nicht aktualisiert werden.",
    },
    statuses: { new: "Neu", contacted: "Kontaktiert", closed: "Abgeschlossen" } satisfies Record<InquiryStatus, string>,
    services: {
      building: "Gebäudereinigung",
      office: "Büroreinigung",
      practice: "Praxisreinigung",
      retail: "Laden- und Geschäftsreinigung",
      stairs: "Treppenhausreinigung",
      sanitary: "Sanitärreinigung",
      "private-household": "Privathaushaltsreinigung",
      entrance: "Eingangs- und Flurreinigung",
      maintenance: "Unterhaltsreinigung",
      other: "Andere Leistung",
    } as Record<string, string>,
  },
  en: {
    language: "Language",
    administration: "Administration",
    loading: "Loading administration...",
    logout: "Log out",
    loggingOut: "Logging out...",
    logoutError: "Logout could not be completed. Please try again.",
    login: {
      title: "Sign in",
      intro: "Sign in with your authorized SB Power account.",
      email: "Email",
      password: "Password",
      showPassword: "Show password",
      hidePassword: "Hide password",
      submit: "Sign in",
      submitting: "Signing in...",
      checking: "Checking session...",
      error: "Email or password is incorrect.",
    },
    list: {
      kicker: "Customer service",
      title: "Contact requests",
      intro: "Review new customer requests and manage their status.",
      summary: "Summary",
      newRequests: "New requests",
      contacted: "Contacted",
      closed: "Closed",
      searchLabel: "Search for a customer",
      searchPlaceholder: "Search for a customer...",
      filterLabel: "Filter by status",
      allStatuses: "All statuses",
      loading: "Loading requests...",
      loadError: "The contact requests could not be loaded.",
      emptyTitle: "No contact requests yet.",
      emptyText: "New requests will appear here as soon as customers submit the form.",
      noResultsTitle: "No matching requests found.",
      noResultsText: "Adjust the search or status filter.",
      previousPage: "Previous",
      nextPage: "Next",
      pageInfo: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      columns: { status: "Status", name: "Name", service: "Service", phone: "Phone", email: "Email", date: "Date", action: "Action" },
      open: "Open request",
      openFor: (name: string) => `Open request from ${name}`,
    },
    detail: {
      back: "Back to requests",
      request: "Contact request",
      received: "Received on",
      customer: "Customer",
      name: "Name",
      phone: "Phone",
      email: "Email",
      service: "Service",
      message: "Message",
      notProvided: "Not provided",
      noMessage: "No message provided.",
      contactCustomer: "Contact customer",
      call: "Call",
      writeEmail: "Write email",
      status: "Status",
      saved: "Status saved",
      loadError: "This contact request could not be loaded.",
      saveError: "The status could not be updated.",
    },
    statuses: { new: "New", contacted: "Contacted", closed: "Closed" } satisfies Record<InquiryStatus, string>,
    services: {
      building: "Building cleaning",
      office: "Office cleaning",
      practice: "Medical practice cleaning",
      retail: "Retail and commercial cleaning",
      stairs: "Stairwell cleaning",
      sanitary: "Sanitary cleaning",
      "private-household": "Private household cleaning",
      entrance: "Entrance and hallway cleaning",
      maintenance: "Maintenance cleaning",
      other: "Other service",
    } as Record<string, string>,
  },
} as const;
