import type { Locale } from "./translations";

export const contactPageTranslations = {
  de: {
    eyebrow: "SB POWER · KONTAKT",
    heroTitleStart: "Wie können wir Ihnen",
    heroTitleAccent: "helfen?",
    heroText: "Sie haben Fragen zu unseren Leistungen oder möchten eine Reinigung anfragen? Kontaktieren Sie uns direkt oder senden Sie uns eine kurze Nachricht.",
    heroPrimary: "Anfrage senden",
    heroSecondary: "Direkt kontaktieren",
    directEyebrow: "DIREKTER KONTAKT",
    directTitle: "Direkt Kontakt aufnehmen",
    directText: "Wählen Sie den Kontaktweg, der für Sie am besten passt.",
    whatsappTitle: "WhatsApp",
    whatsappText: "Schnell und unkompliziert schreiben.",
    whatsappAction: "WhatsApp öffnen",
    phoneTitle: "Telefon",
    phoneText: "Sie möchten direkt mit uns sprechen?",
    phoneAction: "Jetzt anrufen",
    emailTitle: "E-Mail",
    emailText: "Schreiben Sie uns Ihre Anfrage per E-Mail.",
    emailAction: "E-Mail schreiben",
    formEyebrow: "KONTAKTANFRAGE",
    formTitle: "Wie können wir Ihnen helfen?",
    formText: "Senden Sie uns kurz Ihre Anfrage. Wir kontaktieren Sie anschließend persönlich.",
    name: "Name",
    namePlaceholder: "Ihr Name",
    phone: "Telefon",
    phonePlaceholder: "+49 ...",
    email: "E-Mail",
    emailPlaceholder: "name@beispiel.de",
    service: "Gewünschte Leistung",
    choose: "Bitte auswählen",
    other: "Andere Leistung",
    message: "Nachricht",
    messagePlaceholder: "Wie können wir Ihnen helfen?",
    optional: "optional",
    privacy: "Ich habe die Datenschutzerklärung gelesen und stimme der Verarbeitung meiner Angaben zur Bearbeitung meiner Anfrage zu.",
    privacyHelper: "Ihre Angaben werden ausschließlich zur Bearbeitung Ihrer Anfrage verwendet.",
    submit: "Anfrage senden",
    submitting: "Anfrage wird gesendet...",
    successTitle: "Vielen Dank!",
    successText: "Ihre Anfrage wurde erfolgreich übermittelt. Wir kontaktieren Sie so bald wie möglich.",
    newInquiry: "Neue Anfrage senden",
    errorTitle: "Ihre Anfrage konnte nicht gesendet werden.",
    errorText: "Bitte versuchen Sie es erneut oder kontaktieren Sie uns direkt per Telefon, WhatsApp oder E-Mail.",
    errorName: "Bitte geben Sie Ihren Namen ein.",
    errorService: "Bitte wählen Sie eine Leistung aus.",
    errorContact: "Bitte geben Sie eine Telefonnummer oder E-Mail-Adresse an.",
    errorEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    errorPrivacy: "Bitte bestätigen Sie die Datenschutzerklärung.",
  },
  en: {
    eyebrow: "SB POWER · CONTACT", heroTitleStart: "How can we", heroTitleAccent: "help you?", heroText: "Do you have questions about our services or want to request cleaning? Contact us directly or send us a short message.", heroPrimary: "Send inquiry", heroSecondary: "Contact us directly",
    directEyebrow: "DIRECT CONTACT", directTitle: "Contact us directly", directText: "Choose the contact method that suits you best.", whatsappTitle: "WhatsApp", whatsappText: "Message us quickly and easily.", whatsappAction: "Open WhatsApp", phoneTitle: "Phone", phoneText: "Would you like to speak with us directly?", phoneAction: "Call now", emailTitle: "Email", emailText: "Send your inquiry by email.", emailAction: "Write an email",
    formEyebrow: "CONTACT REQUEST", formTitle: "How can we help you?", formText: "Send us a short inquiry and we will contact you personally.", name: "Name", namePlaceholder: "Your name", phone: "Phone", phonePlaceholder: "+49 ...", email: "Email", emailPlaceholder: "name@example.com", service: "Requested service", choose: "Please select", other: "Other service", message: "Message", messagePlaceholder: "How can we help you?", optional: "optional", privacy: "I have read the privacy policy and agree to the processing of my details for this inquiry.", privacyHelper: "Your details are used exclusively to process your inquiry.", submit: "Send inquiry", submitting: "Sending inquiry...", successTitle: "Thank you!", successText: "Your inquiry was submitted successfully. We will contact you as soon as possible.", newInquiry: "Send another inquiry", errorTitle: "Your inquiry could not be sent.", errorText: "Please try again or contact us directly by phone, WhatsApp or email.", errorName: "Please enter your name.", errorService: "Please select a service.", errorContact: "Please provide a phone number or email address.", errorEmail: "Please enter a valid email address.", errorPrivacy: "Please accept the privacy policy.",
  },
  fr: {
    eyebrow: "SB POWER · CONTACT", heroTitleStart: "Comment pouvons-nous", heroTitleAccent: "vous aider ?", heroText: "Vous avez des questions ou souhaitez demander un nettoyage ? Contactez-nous directement ou envoyez-nous un court message.", heroPrimary: "Envoyer une demande", heroSecondary: "Contact direct",
    directEyebrow: "CONTACT DIRECT", directTitle: "Nous contacter directement", directText: "Choisissez le moyen de contact qui vous convient le mieux.", whatsappTitle: "WhatsApp", whatsappText: "Écrivez-nous rapidement et simplement.", whatsappAction: "Ouvrir WhatsApp", phoneTitle: "Téléphone", phoneText: "Vous souhaitez nous parler directement ?", phoneAction: "Appeler", emailTitle: "E-mail", emailText: "Envoyez-nous votre demande par e-mail.", emailAction: "Écrire un e-mail",
    formEyebrow: "DEMANDE DE CONTACT", formTitle: "Comment pouvons-nous vous aider ?", formText: "Envoyez-nous une courte demande. Nous vous contacterons personnellement.", name: "Nom", namePlaceholder: "Votre nom", phone: "Téléphone", phonePlaceholder: "+49 ...", email: "E-mail", emailPlaceholder: "nom@exemple.fr", service: "Service souhaité", choose: "Veuillez choisir", other: "Autre service", message: "Message", messagePlaceholder: "Comment pouvons-nous vous aider ?", optional: "facultatif", privacy: "J’ai lu la politique de confidentialité et j’accepte le traitement de mes données pour cette demande.", privacyHelper: "Vos données sont utilisées exclusivement pour traiter votre demande.", submit: "Envoyer la demande", submitting: "Envoi en cours...", successTitle: "Merci !", successText: "Votre demande a bien été transmise. Nous vous contacterons dès que possible.", newInquiry: "Nouvelle demande", errorTitle: "Votre demande n’a pas pu être envoyée.", errorText: "Veuillez réessayer ou nous contacter directement par téléphone, WhatsApp ou e-mail.", errorName: "Veuillez saisir votre nom.", errorService: "Veuillez choisir un service.", errorContact: "Veuillez indiquer un numéro de téléphone ou une adresse e-mail.", errorEmail: "Veuillez saisir une adresse e-mail valide.", errorPrivacy: "Veuillez accepter la politique de confidentialité.",
  },
  ru: {
    eyebrow: "SB POWER · КОНТАКТЫ", heroTitleStart: "Чем мы можем", heroTitleAccent: "вам помочь?", heroText: "У вас есть вопросы или вы хотите заказать уборку? Свяжитесь с нами напрямую или отправьте короткое сообщение.", heroPrimary: "Отправить заявку", heroSecondary: "Связаться напрямую",
    directEyebrow: "ПРЯМАЯ СВЯЗЬ", directTitle: "Связаться с нами", directText: "Выберите наиболее удобный способ связи.", whatsappTitle: "WhatsApp", whatsappText: "Напишите нам быстро и удобно.", whatsappAction: "Открыть WhatsApp", phoneTitle: "Телефон", phoneText: "Хотите поговорить с нами напрямую?", phoneAction: "Позвонить", emailTitle: "Эл. почта", emailText: "Отправьте заявку по электронной почте.", emailAction: "Написать письмо",
    formEyebrow: "КОНТАКТНАЯ ЗАЯВКА", formTitle: "Чем мы можем вам помочь?", formText: "Отправьте короткую заявку, и мы свяжемся с вами лично.", name: "Имя", namePlaceholder: "Ваше имя", phone: "Телефон", phonePlaceholder: "+49 ...", email: "Эл. почта", emailPlaceholder: "name@example.com", service: "Желаемая услуга", choose: "Выберите", other: "Другая услуга", message: "Сообщение", messagePlaceholder: "Чем мы можем вам помочь?", optional: "необязательно", privacy: "Я прочитал(а) политику конфиденциальности и согласен(на) на обработку данных для этой заявки.", privacyHelper: "Ваши данные используются только для обработки заявки.", submit: "Отправить заявку", submitting: "Заявка отправляется...", successTitle: "Спасибо!", successText: "Ваша заявка успешно отправлена. Мы свяжемся с вами как можно скорее.", newInquiry: "Новая заявка", errorTitle: "Не удалось отправить заявку.", errorText: "Повторите попытку или свяжитесь с нами по телефону, WhatsApp или электронной почте.", errorName: "Введите ваше имя.", errorService: "Выберите услугу.", errorContact: "Укажите номер телефона или адрес электронной почты.", errorEmail: "Введите корректный адрес электронной почты.", errorPrivacy: "Подтвердите политику конфиденциальности.",
  },
  ar: {
    eyebrow: "SB POWER · اتصل بنا", heroTitleStart: "كيف يمكننا", heroTitleAccent: "مساعدتك؟", heroText: "هل لديك أسئلة عن خدماتنا أو ترغب في طلب تنظيف؟ تواصل معنا مباشرة أو أرسل لنا رسالة قصيرة.", heroPrimary: "إرسال طلب", heroSecondary: "تواصل مباشر",
    directEyebrow: "تواصل مباشر", directTitle: "تواصل معنا مباشرة", directText: "اختر طريقة التواصل الأنسب لك.", whatsappTitle: "WhatsApp", whatsappText: "راسلنا بسرعة وسهولة.", whatsappAction: "فتح WhatsApp", phoneTitle: "الهاتف", phoneText: "هل ترغب في التحدث معنا مباشرة؟", phoneAction: "اتصل الآن", emailTitle: "البريد الإلكتروني", emailText: "أرسل لنا طلبك عبر البريد الإلكتروني.", emailAction: "كتابة بريد إلكتروني",
    formEyebrow: "طلب تواصل", formTitle: "كيف يمكننا مساعدتك؟", formText: "أرسل لنا طلباً قصيراً وسنتواصل معك شخصياً.", name: "الاسم", namePlaceholder: "اسمك", phone: "الهاتف", phonePlaceholder: "+49 ...", email: "البريد الإلكتروني", emailPlaceholder: "name@example.com", service: "الخدمة المطلوبة", choose: "يرجى الاختيار", other: "خدمة أخرى", message: "الرسالة", messagePlaceholder: "كيف يمكننا مساعدتك؟", optional: "اختياري", privacy: "قرأت سياسة الخصوصية وأوافق على معالجة بياناتي لهذا الطلب.", privacyHelper: "تستخدم بياناتك حصراً لمعالجة طلبك.", submit: "إرسال الطلب", submitting: "جارٍ إرسال الطلب...", successTitle: "شكراً لك!", successText: "تم إرسال طلبك بنجاح. سنتواصل معك في أقرب وقت ممكن.", newInquiry: "إرسال طلب جديد", errorTitle: "تعذر إرسال طلبك.", errorText: "يرجى المحاولة مرة أخرى أو التواصل معنا مباشرة عبر الهاتف أو WhatsApp أو البريد الإلكتروني.", errorName: "يرجى إدخال اسمك.", errorService: "يرجى اختيار خدمة.", errorContact: "يرجى إدخال رقم هاتف أو بريد إلكتروني.", errorEmail: "يرجى إدخال بريد إلكتروني صالح.", errorPrivacy: "يرجى قبول سياسة الخصوصية.",
  },
} satisfies Record<Locale, Record<string, string>>;
