# Generated by Django 5.2.17 on 2026-09-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('customer_type', models.CharField(choices=[('private', 'Privatkunde'), ('business', 'Unternehmen / Gewerbe')], max_length=20)),
                ('service', models.CharField(max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('language', models.CharField(default='de', max_length=5)),
                ('status', models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('closed', 'Abgeschlossen')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
